### PR TITLE
samples: Translate flaky tests

### LINKED ISSUE #292: com.example.translate.BatchTranslateTextWithGlossaryTests: testBatchTranslateTextWithGlossary failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: b8c8167df27eda3ab1c69f967dcb52fb908b6dcc
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/cbb44aad-12f8-43f4-ac8c-c3c4b3e62c6d), [Sponge](http://sponge2/cbb44aad-12f8-43f4-ac8c-c3c4b3e62c6d)
status: failed
<details><summary>Test output</summary><br><pre>java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1388)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:562)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:443)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:93)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:68)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:133)
	at com.example.translate.BatchTranslateTextWithGlossary.batchTranslateTextWithGlossary(BatchTranslateTextWithGlossary.java:106)
	at com.example.translate.BatchTranslateTextWithGlossaryTests.testBatchTranslateTextWithGlossary(BatchTranslateTextWithGlossaryTests.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre></details>

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #292 #268 #267   ☕️

This is the draft
I do not know it is considered as good test design using base class 

I basically got the idea from the stack overflow answer: 

https://stackoverflow.com/questions/8295100/how-to-re-run-failed-junit-tests-immediately

### CODE REVIEW

File: samples/snippets/src/main/java/com/example/translate/BatchTranslateText.java [hunk 1]
```diff
@@ -85,7 +85,7 @@ public static void batchTranslateText(
           client.batchTranslateTextAsync(request);
 
       System.out.println("Waiting for operation to complete...");
-      BatchTranslateResponse response = future.get(300, TimeUnit.SECONDS);
```
Comment (lesv) [inline samples/snippets/src/main/java/com/example/translate/BatchTranslateText.java:88]: add a random value here

File: samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java [hunk 2]
```diff
@@ -103,7 +103,7 @@ public static void batchTranslateTextWithGlossary(
           client.batchTranslateTextAsync(request);
 
       System.out.println("Waiting for operation to complete...");
-      BatchTranslateResponse response = future.get(300, TimeUnit.SECONDS);
```
Comment (lesv) [inline samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java:106]: add a random value here.

File: samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java [hunk 3]
```diff
@@ -110,7 +110,7 @@ public static void batchTranslateTextWithGlossaryAndModel(
           client.batchTranslateTextAsync(request);
 
       System.out.println("Waiting for operation to complete...");
-      BatchTranslateResponse response = future.get(300, TimeUnit.SECONDS);
```
Comment (lesv) [inline samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java:113]: random value

File: samples/snippets/src/test/java/com/example/translate/Retry.java [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+
+        // implement retry logic here
+        for (int i = 0; i < retryCount; i++) {
+          try {
+            base.evaluate();
+            return;
+          } catch (Throwable t) {
+            caughtThrowable = t;
+            System.out.println(description.getDisplayName() + ": run " + (i + 1) + " failed");
+          }
```
Comment (lesv) [inline samples/snippets/src/test/java/com/example/translate/Retry.java:50]: You should have some kind of random wait here so that multiple operations don't hit at the same time.  (also so that the system can recover if there is a problem.  (ideally it will be exponential, starting at 1, 3, 7, etc.)

Comment (lesv) [reply samples/snippets/src/test/java/com/example/translate/Retry.java:50]: You should do it similarly in the other tests, above.
Start at 1000 * a random value * factor <-- so that multiple tests running at the same time don't do this at the same time. (ie at least one will break free / round).
https://cloud.google.com/storage/docs/exponential-backoff for more info

**Review by lesv — CHANGES_REQUESTED** [review]

File: samples/snippets/src/main/java/com/example/translate/BatchTranslateText.java (hunk 1 above)
Comment (munkhuushmgl) [reply samples/snippets/src/main/java/com/example/translate/BatchTranslateText.java:88]: So Should I generate random between min-max timeout limit; for example,
```
random number between 300 (min)  <= random_number<= 450(max)
```

**Review by lesv — APPROVED** [review]
